### ISSUE TITLE
`spawn': No such file or directory - putty (Errno::ENOENT)

### ISSUE THREAD

**Issue by g13n** [nickryand/vagrant-multi-putty#13]
First of all, kudos for the plugin, this is exactly what I needed.
I have putty.exe in `PATH`, so I'm unable to understand why I get the following error.  Any clues?

```
    C:\Users\my_user\projects>vagrant putty
    C:/Users/my_user/.vagrant.d/gems/gems/vagrant-multi-putty-1.4.4/lib/vagrant-mul
    ti-putty/command.rb:99:in `spawn': No such file or directory - putty (Errno::ENO
    ENT)
            from C:/Users/my_user/.vagrant.d/gems/gems/vagrant-multi-putty-1.4.4/li
    b/vagrant-multi-putty/command.rb:99:in `putty_connect'
            from C:/Users/my_user/.vagrant.d/gems/gems/vagrant-multi-putty-1.4.4/li
    b/vagrant-multi-putty/command.rb:49:in `block in execute'
            from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/p
    lugin/v2/command.rb:226:in `block in with_target_vms'
            from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/p
    lugin/v2/command.rb:220:in `each'
            from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/p
    lugin/v2/command.rb:220:in `with_target_vms'
            from C:/Users/my_user/.vagrant.d/gems/gems/vagrant-multi-putty-1.4.4/li
    b/vagrant-multi-putty/command.rb:47:in `execute'
            from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/c
    li.rb:42:in `execute'
            from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/e
    nvironment.rb:292:in `cli'
            from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.6.5/bin/vagrant:1
    74:in `<main>'
```

**Comment by bmearns** [comment]
based on comment by @nemilya , I solved this by making a symlink to the putty executable (my directory structure is somewhat different) 
'''
mklink C:\Vagrant\embedded\bin\putty.exe "C:\Program Files (x86)\PuTTY\putty.exe"
'''

**Comment by mskadu** [comment]
@bmearns - good idea. Just did this myself and it helped. just to add this will require administrative privileges especially on corporate machines where c: is locked down.
