### ISSUE TITLE
Doesn't work with vagrant 1.7.4

### ISSUE THREAD

**Issue by F21** [nickryand/vagrant-multi-putty#17]
Not sure why this is happening as it worked with vagrant 1.7.3 before.

I have uninstalled and reinstalled version 1.4.4 of the plugin many times.

This is the error message when I try `vagrant putty mymachine`:

```
C:/Users/user/.vagrant.d/gems/gems/vagrant-multi-putty-1.4.4/lib/vagrant-multi-putty/command.rb:99:in `spawn': No such file or directory - putty (Errno::ENOENT)
        from C:/Users/user/.vagrant.d/gems/gems/vagrant-multi-putty-1.4.4/lib/vagrant-multi-putty/command.rb:99:in `putty_connect'
        from C:/Users/user/.vagrant.d/gems/gems/vagrant-multi-putty-1.4.4/lib/vagrant-multi-putty/command.rb:49:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
        from C:/Users/user/.vagrant.d/gems/gems/vagrant-multi-putty-1.4.4/lib/vagrant-multi-putty/command.rb:47:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
```

**Comment by F21** [comment]
Noticed putty was no longer in my PATH for some reason. Readded putty to my PATH and all is well!
