### ISSUE TITLE
"No implicit conversion of nil into String (TypeError)" after upgrading to Vagrant 2.0.0

### ISSUE THREAD

**Issue by bradisbell** [nickryand/vagrant-multi-putty#32]
When running `vagrant putty`, I'm now getting the following error:

```
C:/Users/Brad/.vagrant.d/gems/2.3.4/gems/vagrant-multi-putty-1.6.0/lib/vagrant-multi-putty/command.rb:114:in `read'
: no implicit conversion of nil into String (TypeError)
        from C:/Users/Brad/.vagrant.d/gems/2.3.4/gems/vagrant-multi-putty-1.6.0/lib/vagrant-multi-putty/command.rb:
114:in `block in get_putty_key_file'
        from C:/Users/Brad/.vagrant.d/gems/2.3.4/gems/vagrant-multi-putty-1.6.0/lib/vagrant-multi-putty/command.rb:
112:in `tap'
        from C:/Users/Brad/.vagrant.d/gems/2.3.4/gems/vagrant-multi-putty-1.6.0/lib/vagrant-multi-putty/command.rb:
112:in `get_putty_key_file'
        from C:/Users/Brad/.vagrant.d/gems/2.3.4/gems/vagrant-multi-putty-1.6.0/lib/vagrant-multi-putty/command.rb:
94:in `putty_connect'
        from C:/Users/Brad/.vagrant.d/gems/2.3.4/gems/vagrant-multi-putty-1.6.0/lib/vagrant-multi-putty/command.rb:
53:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/plugin/v2/command.rb:235:in `block i
n with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/plugin/v2/command.rb:229:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/plugin/v2/command.rb:229:in `with_ta
rget_vms'
        from C:/Users/Brad/.vagrant.d/gems/2.3.4/gems/vagrant-multi-putty-1.6.0/lib/vagrant-multi-putty/command.rb:
51:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:308:in `cli'
        from C:/HASHIC~1/Vagrant/embedded/gems/gems/vagrant-2.0.0/bin/vagrant:138:in `<main>'
```

I upgraded to Vagrant 2.0.0, and that's when this started occurring.

**Comment by bradisbell** [comment]
Disregard... not sure what happened or what I did while trying to debug this, but it's working again.  Thanks for the great plugin!
